
const characterData = [
{
name: 'notNull/string',
race: 'notNull/string',
class: 'notNull/string',
level: 'notNull/interger',
alignment: 'notNull/string',
hitpoints: 'notNull/interger',
experience_points: 'notNull/interger',
initiative: 'notNull/interger',
attack_modifier: 'notNull/interger',
speed: 'notNull/interger',
strength: 'notNull/interger',
dexterity: 'notNull/interger',
constitution: 'notNull/interger',
intelligence: 'notNull/interger',
wisdom: 'notNull/interger',
charisma: 'notNull/interger',
spells: 'canNull/string',
cantrips: 'canNull/string',
proficiencies: 'canNull/string',
personality: 'canNull/string',
ideals: 'canNull/string',
bonds: 'canNull/string',
flaws: 'canNull/string',
features: 'canNull/string',
traits: 'canNull/string',
},
]

// {
//     name: 'notNull/string',
//     race: 'notNull/string',
//     class: 'notNull/string',
//     level: 'notNull/interger',
//     alignment: 'notNull/string',
//     hitpoints: 'notNull/interger',
//     experience_points: 'notNull/interger',
//     initiative: 'notNull/interger',
//     attack_modifier: 'notNull/interger',
//     speed: 'notNull/interger',
//     strength: 'notNull/interger',
//     dexterity: 'notNull/interger',
//     constitution: 'notNull/interger',
//     intelligence: 'notNull/interger',
//     wisdom: 'notNull/interger',
//     charisma: 'notNull/interger',
//     spells: 'canNull/string',
//     cantrips: 'canNull/string',
//     proficiencies: 'canNull/string',
//     personality: 'canNull/string',
//     ideals: 'canNull/string',
//     bonds: 'canNull/string',
//     flaws: 'canNull/string',
//     features: 'canNull/string',
//     traits: 'canNull/string',
//     },